### ISSUE TITLE
Porting to the new spec?

### ISSUE THREAD

**Issue by jammm** [jamornsriwasansak/mortar#1]
Hello Jamorn! First of all thank you for the great contribution to the open source community with this path tracer. Not many path tracers out there actually use the Vulkan RT extensions at the moment.
Recently, Khronos announced [1] the final spec of Vulkan RT extensions that this renderer uses. Are there any plans to update the code to work with the new spec?

Cheers!

[1] - https://www.khronos.org/blog/vulkan-ray-tracing-final-specification-release

**Comment by jamornsriwasansak** [comment]
I believed it has already followed the new spec.

**Comment by jamornsriwasansak** [comment]
Thanks. I also wanted to update the framework. However, every time the Vulkan's RT extension updates, it breaks something. At this point, I am too lazy to update the code. I might revisit this project in the future.

I'd like to note even with the new specification. The api largely remains the same. You can try editing by yourself but no promise.

**Comment by jamornsriwasansak** [comment]
I know that this comment is almost a year late but the Vulkan backend has completely been ported to new spec.
Path tracer is still being ported from glsl to hlsl but the backend works as intended.

**Comment by jammm** [comment]
Awesome :) Thanks for this!
